# Матрицы и NumPy


## Библиотека NumPy ##

In [2]:
import numpy as np

Матрица размером 1 на 3 (или вектор-строка)

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


Матрица размером 2 на 3

In [3]:
b = np.array([[1,2,3],
              [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


Матрица размером 3 на 1 (или вектор-столбец)

In [ ]:
c = np.array([[7],
              [8],
              [9]])

print(c)

[[7]
 [8]
 [9]]


Размеры матриц

In [ ]:
print(a.shape)
print(b.shape)
print(c.shape)

(3,)
(2, 3)
(3, 1)


Матрицы из базовых типов

In [ ]:
my_list = [1,2,3,4,5]
print('my_list = ', my_list)
my_tuple = (6,7,8,9,10)
print('my_tuple = ', my_tuple)
my_range = range(100,110,2)
print('my_range = ', my_range)
d = np.array([my_list, my_tuple, my_range])
print('d = ', d, sep='\n')

my_list =  [1, 2, 3, 4, 5]
my_tuple =  (6, 7, 8, 9, 10)
my_range =  range(100, 110, 2)
d = 
[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [100 102 104 106 108]]


Тип матрицы

In [ ]:
a = np.array([1, 2, 3])
print('type (a) = ', a.dtype)
print('a = ', a)

b = np.array([1, 2, 3/2])
print('type (b) = ', b.dtype)
print('b = ', b)

c = np.array(['привет',',', 'мир!'])
print('type (c) = ', c.dtype)
print('c = ', c)

type (a) =  int32
a =  [1 2 3]
type (b) =  float64
b =  [1.  2.  1.5]
type (c) =  <U6
c =  ['привет' ',' 'мир!']


Нулевая матрица

In [ ]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


Матрица из единиц

In [ ]:
print(np.ones((4,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Единичная матрица

In [ ]:
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Матрица из range

In [ ]:
print(np.arange(12))
print(np.arange(100,124,2))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[100 102 104 106 108 110 112 114 116 118 120 122]


Изменение размера

In [ ]:
a = np.arange(100,124,2)
b = a.reshape(4,3)
print('a = ', a)
print('b = ', b, sep='\n')

a =  [100 102 104 106 108 110 112 114 116 118 120 122]
b = 
[[100 102 104]
 [106 108 110]
 [112 114 116]
 [118 120 122]]


In [ ]:
n = 5
m = 6
a = np.arange(n*m).reshape(n,m)
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


Индексация и срезы

In [ ]:
print(a[1,2], a[3,3], a[-1,4])

8 21 28


In [ ]:
print(a[1])

[ 6  7  8  9 10 11]


In [ ]:
print(a[:2])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [ ]:
print(a[1::2])

[[ 6  7  8  9 10 11]
 [18 19 20 21 22 23]]


In [ ]:
print(a[:,1])

[ 1  7 13 19 25]


In [ ]:
print(a[1:3,2:5])

[[ 8  9 10]
 [14 15 16]]


Транспонирование матрицы

In [ ]:
print('a = ', a, '', sep='\n')
print(a.shape, '\n')
b=a.T
print('b = ', b, '', sep='\n')
print(b.shape)

a = 
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]

(5, 6) 

b = 
[[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]

(6, 5)


Склейка матриц

In [ ]:
n=3
m=2
a = np.arange(n*m).reshape(n,m)
b = np.arange(100, 100+n*m).reshape(n,m)
print('a = ', a, '', sep='\n')
print('b = ', b, '', sep='\n')

c = np.hstack([a,b])
print('c = ', c, '', sep='\n')

d = np.vstack([a,b])
print('d = ', d, '', sep='\n')

e = np.hstack([a]*5)
print('e = ', e, sep='\n')

a = 
[[0 1]
 [2 3]
 [4 5]]

b = 
[[100 101]
 [102 103]
 [104 105]]

c = 
[[  0   1 100 101]
 [  2   3 102 103]
 [  4   5 104 105]]

d = 
[[  0   1]
 [  2   3]
 [  4   5]
 [100 101]
 [102 103]
 [104 105]]

e = 
[[0 1 0 1 0 1 0 1 0 1]
 [2 3 2 3 2 3 2 3 2 3]
 [4 5 4 5 4 5 4 5 4 5]]


# Задания #


Далее представлено 15 заданий.
* Для оценки 5 необходимо сделать не менее 14 заданий.
* Для оценки 4 необходимо сделать не менее 9 заданий.
* Для оценки 3 необходимо сделать не менее 4 заданий.

### Задание 1 ###
Напишите функцию __snake1(n,m)__, которая возвращает матрицу $n \times m$, заполненную следующим образом (пример для $n=4$, $m=3$):
```python
    [[1,2,3],
    [6,5,4],
    [7,8,9],
    [12,11,10]]
 ```

In [ ]:
def snake1(n, m):
    for i in range(n):
        
    a = np.array()

print(snake1(4,3))

None


### Задание 2 ###
Напишите функцию __snake2(n)__, которая возвращает матрицу $n \times n$, заполненную следующим образом (пример для $n=4$):
```python
    [[1,2,9,10],
    [4,3,8,11],
    [5,6,7,12],
    [15,14,13]]
 ```

In [ ]:
def right(field,i,  start, n, col) -> tuple:
    for x in range(len(field[i][start : start + n])):
        field[i][x] = col
        col += 1

    return (start + n, col)

def left(field,i,  start, n, col) -> tuple:
    for x in range(len(field[i][start : start + n]), 0, -1):
        field[i][x + start] = col
        col += 1

    return (start + n, col)

def snake2(n, m):
    pass

print(snake2(4,5))

None


### Задание 3 ###
Напишите функцию __snake3(n,m)__, которая возвращает матрицу $n \times m$, заполненную следующим образом (пример для $n=4$, $m=5$):

```python
    [[1,2,3,4,5],
    [14,15,16,17,6],
    [13,20,19,18,7],
    [12,11,10,9,8]]
 ```

In [69]:
def isaval(field, i, j):
    return (i < field.shape[0] and i >= 0) and (j < field.shape[1] and j >= 0) and not field[i,j]

def snake3(n, m):
    ans = np.zeros((n, m), np.int32)
    i, j, col = 0, 0, 1
    while col < n * m: 
        while isaval(ans, i, j+1): 
            ans[i][j] = col
            col += 1
            j += 1
        while isaval(ans, i+1, j):
            ans[i][j] = col
            col += 1
            i += 1
        while isaval(ans, i, j-1): 
            ans[i][j] = col
            col += 1
            j -= 1
        while isaval(ans, i-1, j):
            ans[i][j] = col
            col += 1
            i -= 1
    ans[i][j] = n * m
    return ans

print(snake3(4, 5))

[[ 1  2  3  4  5]
 [14 15 16 17  6]
 [13 20 19 18  7]
 [12 11 10  9  8]]


### Задание 4 ###
Напишите функцию __paraboloid(n)__, которая возвращает матрицу размера $2n + 1 \times 2n +1$,
для которой значение в ячейке [i,j] равняется расстоянию от точки с координатами $(0,0)$ до точки с координатами $(\frac{i-n}{n},\frac{j-n}{n})$. Расстояние - это верщественное число. Сделайте так, чтобы при печати выводилось только два занка после запятой.

In [ ]:
def paraboloid(n):
    pass

print(paraboloid(4))

None


### Задание 5 ###
Напишите функцию __chess_queen(n,m,i,j)__, которая возвращает матрицу размера $n \times m$, 
заполненную 0 и 1 по следующему правилу: 

Предположим, мы имеем шахматную доску размером $n \times m$ и в ячейке $(i,j)$ стоит ферзь. Клетки нумеруются с $0$ из левого верхнего угла.

В клетку $(i,j)$ необходимо поставить 2. Необходимо поставить $1$ на все клетки, куда ферзь может ударить. В остальные клетки необходимо поставить $0$.

Пример __chess_queen(3,4,2,2)__:
```python
    [[1,0,1,0],
    [0,1,1,1],
    [1,1,2,1]]
```

In [52]:
class Dot:
    def __init__(self, pos, dir):
        self.pos = pos
        self.dir = dir
        self.col = 0

    def jump(self) -> None:
        self.pos[0] += self.dir[0]
        self.pos[1] += self.dir[1]
        self.col += 1
        
check = lambda i, j, n, m: (i >= 0 and i < n) and (j >= 0 and j < m)

def tryjump(field, i, j):
    return check(i,j, field.shape[0], field.shape[1]) and not field[i][j]



def chess_queen(n,m,i,j):
    q = list()
    field = np.zeros((n,m))
    field[i,j] = 2
    q.append(Dot([i, j], [-1, 0]))
    q.append(Dot([i, j], [0, -1]))
    q.append(Dot([i, j], [1, 0]))
    q.append(Dot([i, j], [0, 1]))
    q.append(Dot([i, j], [-1, -1]))
    q.append(Dot([i, j], [-1, 1]))
    q.append(Dot([i, j], [1, 1]))
    q.append(Dot([i, j], [1, -1]))

    while (len(q)):
        a = q[0]
        q = q[1:]
        a.jump()
        if (tryjump(field, a.pos[0], a.pos[1])):
            field[a.pos[0], a.pos[1]] = 1
            q.append(a)

    return field


print(chess_queen(3,4,2,2))

[[1. 0. 1. 0.]
 [0. 1. 1. 1.]
 [1. 1. 2. 1.]]


### Задание 6 ###

Напишите функцию __chess_knight(n,m,i,j)__, которая возвращает матрицу размера $n \times m$, заполненную целами числами 
следующим образом. На поле с координатами $i \times j$ ставится шахматный конь. Значение в ячейке $a \times b$ раняется __минимальному__ количеству ходов конем, которое надо совершить, чтобы из поля $i \times j$ попасть в поле $a \times b$.
Если в поле поасть невозможно, то значение в соотвествующей ячейке должно быть равно $-1$.

Пример  __chess_knight(3,3,0,0)__:
```python
    [[0,3,2],
    [3,-1,1],
    [2,1,4]]
```

In [56]:
import numpy as np

class Dot:
    def __init__(self, pos, dir):
        match pos:
            case list():
                self.pos = pos.copy()
                self.col = 0
            case Dot():
                self.pos = pos.pos.copy()
                self.col = pos.col
        self.dir = dir

    def jump(self) -> None:
        self.pos[0] += self.dir[0]
        self.pos[1] += self.dir[1]
        self.col += 1


check = lambda i, j, n, m: (i >= 0 and i < n) and (j >= 0 and j < m)


def tryjump(field, i, j):
    return check(i, j, field.shape[0], field.shape[1]) and (field[i][j] == -1)


def adddots(q, i, j, MOVES, origin:Dot = None):
    if (origin == None):
        for el in MOVES:
            q.append(Dot([i, j], el))
    else:
        for el in MOVES:
            q.append(Dot(origin, el))

def chess_knight(n, m, i, j):
    q = list()
    field = np.zeros((n, m))
    for el in range(len(field)):
        field[el] -= 1

    field[i, j] = 0

    MOVES = [[2, 1], [2, -1], [1, 2], [1, -2], [-1, 2], [-1, -2], [-2, 1], [-2, -1]]
    adddots(q, i, j, MOVES)

    while (len(q)):
        a = q[0]
        if (a.pos == [2,1] and a.dir == [-2, 1]):
            print("Hello there!")
        q = q[1:]
        a.jump()
        if (tryjump(field, a.pos[0], a.pos[1])):
            field[a.pos[0], a.pos[1]] = a.col
            adddots(q, a.pos[0], a.pos[1], MOVES, a)

    return field


print(chess_knight(3, 3, 0, 0))

[[0. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### Задание 7 ###
Напишите функцию __generate(a,b,c)__, которая получает на вход три матрицы:

Матрица __a__ -- произвольная матрица из $0$ и $1$ имеющая размер $n \times m$

Матрицы __b__ и __c__ -- произвольные матрицы имеющие __одинаковый размер__ $p \times q$.

Функция должна вернуть матрицу размера  $np \times mq$, построенную по следующему правилу:

Вместо $0$ матрицы __a__ подставляется матрица __b__, вместо $1$ матрицы __a__ подставляется матрица __с__.

Пример:
```python
    a = np.array([[1,1,0],
                  [0,1,1]])
                  
    b = np.array([[1,2],
                  [3,4]])
                  
    c = np.array([[3,3],
                  [3,3]])
    
    generate(a,b,c) ->
    [[3,3,3,3,1,2]
     [3,3,3,3,3,4]
     [1,2,3,3,3,3]
     [3,4,3,3,3,3]]
```

In [30]:
a = np.array([[1,1,0],
              [0,1,1]])
                  
b = np.array([[1,2, 5],
              [3,4, 6]])
                  
c = np.array([[3,3, 7],
              [3,3, 7]])

def get_row(row, b, c):
    f = [b,c]
    tmp = f[row[0]]
    for el in row[1:]:
        tmp = np.hstack([tmp,f[int(el)]])
    return tmp    

def generate(a,b,c):
    f:list[np.array] = [b, c]
    ans = np.array(get_row(a[0], b, c))
    for row in a[1:]:
        ans = np.vstack([ans,get_row(row,b,c)])

    return ans


print(generate(a,b,c))

[[3 3 7 3 3 7 1 2 5]
 [3 3 7 3 3 7 3 4 6]
 [1 2 5 3 3 7 3 3 7]
 [3 4 6 3 3 7 3 3 7]]


### Задание 8 ###
Реализуйте (без использования встроенных функций numpy) функцию __is_symmetric(A)__, которая проверят является ли матрица A симметричной, то A[i,j] == A[j,i] для любых [i,j]

Примеры:
```python
A = [[1,2,3],
     [2,5,4],
     [3,4,-1]
    ]

is_symmetric(A) == True

B = [[1,2,3],
     [2,5,4],
     [20,4,-1]
    ]

is_symmetric(B) == False

C = [[1,2,3],
     [2,5,4]
    ]

is_symmetric(C) == False
```

In [34]:
def is_symmetric(A):
    for i in range(len(A)):
        for j in range(i + 1, len(A[i])):
            if (A[i][j] != A[j][i]):
                return False
            
    return True

True

### Задание 9 ###
Реализуйте (без использования встроенных функций numpy) функцию __transpose(A)__, возвращает транспонированную матрицу A

In [ ]:
def transpose(A):
    for i in range(len(A)):
        for j in range(i + 1, len(A[i])):
            A[i][j], A[j][i] = A[j][i], A[i][j]
    return A

### Задание 10 ###
Напишите (без использования встроенных функций numpy) функцию __mult(A,B)__, возвращает произведение матриц A и B. Если матрицы умножить нельзя, то можно возвращать ошибку.

Визуализация умножения матриц: http://matrixmultiplication.xyz/

In [ ]:
def transpose(A):
    for i in range(len(A)):
        for j in range(i + 1, len(A[i])):
            A[i][j], A[j][i] = A[j][i], A[i][j]
    return A

def mult(A,B):
    if len(A[0]) != len(B):
        raise IndexError
    n, m = len(A), len(B[0])
    ans = np.zeros((n, m), np.int32)
    for i in range(n):
        for j in range(m):
            ans[i][j] = A[i] @ B.T[j]

    return ans


В задачах 11,12,13,14,15 __приветствуется__ использование встроенных функций numpy.

Постарайтесь сделать и компактный элегантный код. 

### Задание 11 ###

Дана матрица $A$ размера $n \times m$ (n - строк и m - столбцов). Сформируйте две матрицы $B$ и $C$. Первая размера $n \times 1$, каждый элемент которой равен __максимальному__ в соотвествующей строке $A$. Вторая матрица размера $1 \times m$, каждый элемент которой равен __минимальному__ в соотвествующем столбце $A$.

Например, если 
```python
А = [[1,3],
    [4,1],
    [5,6]]
```
то 
```python
B = [[3],
    [4],
    [6]]

C = [[1,1]]
```


In [48]:
A = np.array([[1,3],
    [4,1],
    [5,6]])

B = np.array([row.max() for row in A]).reshape(A.shape[0],1)
C = np.array([row.min() for row in A.T]).reshape(1, A.shape[1])

array([[1, 1]])

### Задание 12 ###

Дана матрица $A$ размера $n \times m$ (n - строк и m - столбцов). Сформируйте две матрицы $B$ и $C$. Первая размера $n \times 1$, каждый элемент которой равен __сумме__ в соотвествующей строке $A$. Вторая матрица размера $1 \times m$, каждый элемент которой равен __произведению__ в соотвествующем столбце $A$.

Например, если 
```python
А = [[1,3],
    [4,1],
    [5,6]]
```
то 
```python
B = [[4],
    [5],
    [11]]

C = [[20,18]]
```

In [63]:
def sum(A:np.array) -> int:
    ans = 0
    for el in A:
        ans += el
    return ans

def sq(A:np.array) -> int:
    ans = 1
    for el in A:
        ans *= el
    return ans

B = np.array([sum(row) for row in A]).reshape(A.shape[0],1)
C = np.array([sq(row) for row in A.T]).reshape(1, A.shape[1])


(array([[ 4],
        [ 5],
        [11]]),
 array([[20, 18]]))

### Задание 13 ###

Дана матрица $А$. Необходимо ее нормировать, т.е. поделить каждый элемент на сумму всех элементов матрицы

In [ ]:
A = A.astype(np.float64)
for i in range(len(A)):
    A[i] = np.array([A[i,j]/A[i].sum() for j in range(len(A[i]))])


### Задание 14 ###
Дана матрица $А$. Необходимо нормировать каждый ее столбец, т.е. поделить каждый элемент на столбца на сумму элементов столбца.

In [62]:
A = A.T
A = A.astype(np.float64)
for i in range(len(A)):
    A[i] = np.array([A[i,j]/A[i].sum() for j in range(len(A[i]))])
A = A.T

A

array([[0.1, 0.3],
       [0.4, 0.1],
       [0.5, 0.6]])

### Задание 15 ###
Дана матрица $A$. Необходимо столбцы с четными индексами умножить на 5, с нечетными - поделить на -5

In [ ]:
A = np.array()

A.fliplr()
for i in range(len(A)):
    A[i] = A[i]/5

print (A)